[package]
name = 'gh-actions-rust'
version = '0.0.1'
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = {version = "0.10", features = ["luajit", "module", "serialize"]}
serde = "1.0"
serde_yaml = "0.9"
